<?php


namespace backend\controllers;


use appxq\sdii\utils\VarDumper;
use common\models\Options;
use cpn\chanpan\classes\CNMessage;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use backend\models\User;

class Admin2Controller extends Controller
{
    public function beforeAction($action)
    {

        if($action->id = 'index'){
            $this->layout = 'admin';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render("index");
    }
    public function actionUser(){
        $query = User::find()
            ->select(['user.*','profile.*'])
            ->innerJoin('profile','profile.user_id=user.id')
            ->orderBy(['user.id'=>SORT_DESC]);

        $dataProvider = new ActiveDataProvider([
            'query'=>$query,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        return $this->render("user",[
            'dataProvider'=>$dataProvider
        ]);
    }
    public function actionPrice(){
        $price = 0;
        if(isset(\Yii::$app->params['totalPrice'])){
            $price = \Yii::$app->params['totalPrice'];
        }

        if(\Yii::$app->request->post()){
            $price = \Yii::$app->request->post('price');
            $options = Options::find()->where(['label'=>'totalPrice'])->one();
            $options->value = $price;
            if($options->save()){
                return CNMessage::getSuccess("แก้ไขข้อมูลสำเร็จ");
            }else{
                return CNMessage::getError("แก้ไขข้อมูลไม่สำเร็จ");
            }
        }
        return $this->render("price",[
            'price'=>$price
        ]);
    }
}